"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SAMPLE_NORMAL_INVESTIGATION = exports.DEMO_INVESTIGATION = void 0;
exports.DEMO_INVESTIGATION = {
    id: 'INV-8391',
    name: 'Trade Finance Rogue Hijack',
    description: 'Autonomous investigation of suspicious invoice transfer activity on tradechannel. A rogue identity from Org3MSP intercepted an invoice asset and redirected ownership outside the approved endorsement policy.',
    targetAssetId: 'INVOICE-8391',
    targetTransactionId: 'a7f3c2d1e8b94f6a2c1d3e5f7a9b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6',
    channel: 'tradechannel',
    chaincode: 'asset-transfer',
    createdAt: '2026-09-27T09:20:00.000Z',
    riskLevel: 'CRITICAL',
    summary: 'Three anomalies detected. A rogue identity (rogue-agent@Org3MSP) performed an unauthorized asset transfer of invoice INVOICE-8391, bypassing the approved endorsement policy. Velocity outlier detected: 3 ownership changes in 4 minutes versus the expected rate of 1 per business day. Endorsement mismatch: transaction was signed by Org3MSP which is not a member of the asset-transfer endorsement policy for this asset class.',
    expectedWorkflow: [
        'Supplier (Org1) creates invoice INVOICE-8391',
        'Supplier transfers invoice to Bank (Org2) for payment processing',
        'Bank (Org2) approves and marks invoice DELIVERED',
    ],
    observedWorkflow: [
        'Supplier (Org1) creates invoice INVOICE-8391 — CREATED',
        'Supplier transfers invoice to Bank (Org2) — NORMAL',
        'Bank (Org2) transfers invoice to Distributor (Org2) — UNEXPECTED',
        'Rogue agent (Org3) transfers invoice to UnknownEntity — ANOMALOUS',
    ],
    transactions: [
        {
            transactionId: 'b2c4d6e8f0a1b3c5d7e9f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3',
            blockNumber: 5,
            timestamp: '2026-09-27T09:20:01.000Z',
            channel: 'tradechannel',
            chaincode: 'asset-transfer',
            function: 'CreateAsset',
            creator: {
                identity: 'supplier-admin',
                organization: 'Org1',
                msp: 'Org1MSP',
            },
            asset: {
                id: 'INVOICE-8391',
                type: 'INVOICE',
                previousOwner: '',
                previousOrganization: '',
                newOwner: 'supplier-admin',
                newOrganization: 'Org1MSP',
                status: 'CREATED',
                metadata: { amount: '$450,000', currency: 'USD', buyer: 'GlobalRetail' },
            },
            args: ['INVOICE-8391', 'INVOICE', 'Trade finance invoice for shipment SHP-4421', '{"amount":"$450,000","currency":"USD","buyer":"GlobalRetail","dueDate":"2026-10-27"}'],
            endorsers: ['Org1MSP', 'Org2MSP'],
            validationCode: 'VALID',
            rawPayload: {
                payloadHash: '0x8f3c2a1b4d',
                certIssuer: 'ca.org1.example.com',
            },
        },
        {
            transactionId: 'c3d5e7f9a1b3c5d7e9f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5',
            blockNumber: 6,
            timestamp: '2026-09-27T09:21:15.000Z',
            channel: 'tradechannel',
            chaincode: 'asset-transfer',
            function: 'TransferAsset',
            creator: {
                identity: 'supplier-admin',
                organization: 'Org1',
                msp: 'Org1MSP',
            },
            asset: {
                id: 'INVOICE-8391',
                type: 'INVOICE',
                previousOwner: 'supplier-admin',
                previousOrganization: 'Org1MSP',
                newOwner: 'bank-officer',
                newOrganization: 'Org2MSP',
                status: 'IN_TRANSIT',
            },
            args: ['INVOICE-8391', 'bank-officer', 'Org2MSP'],
            endorsers: ['Org1MSP', 'Org2MSP'],
            validationCode: 'VALID',
        },
        {
            transactionId: 'd4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6',
            blockNumber: 7,
            timestamp: '2026-09-27T09:22:44.000Z',
            channel: 'tradechannel',
            chaincode: 'asset-transfer',
            function: 'TransferAsset',
            creator: {
                identity: 'bank-officer',
                organization: 'Org2',
                msp: 'Org2MSP',
            },
            asset: {
                id: 'INVOICE-8391',
                type: 'INVOICE',
                previousOwner: 'bank-officer',
                previousOrganization: 'Org2MSP',
                newOwner: 'distributor-clerk',
                newOrganization: 'Org2MSP',
                status: 'IN_TRANSIT',
            },
            args: ['INVOICE-8391', 'distributor-clerk', 'Org2MSP'],
            endorsers: ['Org1MSP', 'Org2MSP'],
            validationCode: 'VALID',
            rawPayload: {
                note: 'Internal org transfer initiated before expected delivery milestone',
            },
        },
        {
            transactionId: 'a7f3c2d1e8b94f6a2c1d3e5f7a9b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6',
            blockNumber: 8,
            timestamp: '2026-09-27T09:24:09.000Z',
            channel: 'tradechannel',
            chaincode: 'asset-transfer',
            function: 'TransferAsset',
            creator: {
                identity: 'rogue-agent',
                organization: 'Org3',
                msp: 'Org3MSP',
            },
            asset: {
                id: 'INVOICE-8391',
                type: 'INVOICE',
                previousOwner: 'distributor-clerk',
                previousOrganization: 'Org2MSP',
                newOwner: 'unknown-entity-7742',
                newOrganization: 'ExternalMSP',
                status: 'IN_TRANSIT',
            },
            args: ['INVOICE-8391', 'unknown-entity-7742', 'ExternalMSP'],
            endorsers: ['Org3MSP'],
            validationCode: 'VALID',
            rawPayload: {
                note: 'Single-org endorsement — Org3MSP only. Expected policy requires Org1MSP+Org2MSP.',
            },
        },
    ],
    anomalies: [
        {
            id: 'ANOM-001',
            severity: 'CRITICAL',
            type: 'UNAUTHORIZED_TRANSFER',
            title: 'Unauthorized ownership transfer by out-of-policy identity',
            description: 'Transaction a7f3c2d1 was submitted by rogue-agent@Org3MSP and transferred INVOICE-8391 to unknown-entity-7742@ExternalMSP. Org3MSP is not a member of the endorsement policy for asset-transfer on tradechannel. This transfer bypassed the required Org1MSP+Org2MSP endorsement policy.',
            evidenceTransactionIds: ['a7f3c2d1e8b94f6a2c1d3e5f7a9b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6'],
            recommendation: 'Freeze asset INVOICE-8391 immediately. Investigate rogue-agent credentials issued by Org3MSP CA. Review channel endorsement policy configuration. Audit all Org3MSP transactions on tradechannel in the last 30 days.',
        },
        {
            id: 'ANOM-002',
            severity: 'HIGH',
            type: 'VELOCITY_OUTLIER',
            title: 'Abnormal transaction velocity — 3 ownership changes in 4 minutes',
            description: 'INVOICE-8391 changed ownership 3 times between 09:21 and 09:24 UTC (248 seconds). Historical baseline for this asset class is 1 ownership change per business day. This 3-transfer burst deviates from expected workflow by 99.7%.',
            evidenceTransactionIds: [
                'c3d5e7f9a1b3c5d7e9f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5',
                'd4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6',
                'a7f3c2d1e8b94f6a2c1d3e5f7a9b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6',
            ],
            recommendation: 'Implement rate limiting on TransferAsset for high-value invoice assets. Add chaincode-level business rule: maximum 1 transfer per invoice per 24-hour window unless pre-approved.',
        },
        {
            id: 'ANOM-003',
            severity: 'HIGH',
            type: 'ENDORSEMENT_MISMATCH',
            title: 'Single-organization endorsement on multi-party asset',
            description: 'The anomalous transaction a7f3c2d1 was endorsed only by Org3MSP. All previous transactions on INVOICE-8391 required and received endorsement from both Org1MSP and Org2MSP. The endorsement policy for asset-transfer chaincode requires a minimum of two organizations.',
            evidenceTransactionIds: ['a7f3c2d1e8b94f6a2c1d3e5f7a9b0c2d4e6f8a0b2c4d6e8f0a2b4c6d8e0f2a4b6'],
            recommendation: 'Review how this transaction passed orderer validation with a single endorsement. This may indicate an endorsement policy misconfiguration or a policy update that was not reviewed. Audit recent channel configuration transactions.',
        },
    ],
};
exports.SAMPLE_NORMAL_INVESTIGATION = {
    id: 'INV-1002',
    name: 'Standard Supply Chain Asset Audit',
    description: 'Routine investigation of SHIP-2841 electronics cargo container. Verified full provenance from Manufacturer to Retailer.',
    targetAssetId: 'SHIP-2841',
    targetTransactionId: 'e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0',
    channel: 'tradechannel',
    chaincode: 'asset-transfer',
    createdAt: '2026-09-27T10:00:00.000Z',
    riskLevel: 'LOW',
    summary: 'No anomalies detected. Asset SHIP-2841 followed standard 4-stage supply chain lifecycle. Endorsement policies met on all 3 transitions.',
    expectedWorkflow: [
        'Manufacturer (Org1) creates SHIP-2841',
        'Manufacturer transfers to Logistics (Org2)',
        'Logistics transfers to Retailer (Org3)',
    ],
    observedWorkflow: [
        'Manufacturer (Org1) creates SHIP-2841 — VALID',
        'Manufacturer transfers to Logistics (Org2) — VALID',
        'Logistics transfers to Retailer (Org3) — VALID',
    ],
    transactions: [
        {
            transactionId: 'f1a3b5c7d9e1f3a5b7c9d1e3f5a7b9c1d3e5f7a9b1c3d5e7f9a1b3c5d7e9f1a3',
            blockNumber: 1,
            timestamp: '2026-09-27T08:00:00.000Z',
            channel: 'tradechannel',
            chaincode: 'asset-transfer',
            function: 'CreateAsset',
            creator: { identity: 'mfg-admin', organization: 'Org1', msp: 'Org1MSP' },
            asset: { id: 'SHIP-2841', type: 'CONTAINER', previousOwner: '', previousOrganization: '', newOwner: 'mfg-admin', newOrganization: 'Org1MSP', status: 'CREATED' },
            args: ['SHIP-2841', 'CONTAINER', 'Electronics container', '{"weight":"1200kg"}'],
            endorsers: ['Org1MSP', 'Org2MSP'],
            validationCode: 'VALID',
        },
        {
            transactionId: 'e8f0a2b4c6d8e0f2a4b6c8d0e2f4a6b8c0d2e4f6a8b0c2d4e6f8a0b2c4d6e8f0',
            blockNumber: 2,
            timestamp: '2026-09-27T08:30:00.000Z',
            channel: 'tradechannel',
            chaincode: 'asset-transfer',
            function: 'TransferAsset',
            creator: { identity: 'mfg-admin', organization: 'Org1', msp: 'Org1MSP' },
            asset: { id: 'SHIP-2841', type: 'CONTAINER', previousOwner: 'mfg-admin', previousOrganization: 'Org1MSP', newOwner: 'logistics-driver', newOrganization: 'Org2MSP', status: 'IN_TRANSIT' },
            args: ['SHIP-2841', 'logistics-driver', 'Org2MSP'],
            endorsers: ['Org1MSP', 'Org2MSP'],
            validationCode: 'VALID',
        },
    ],
    anomalies: [],
};
